<?php

/*
 * This file is part of the AlcyonCoreBundle package.
 *
 * (c) David DE SOUSA <d.desousa@alcyon.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
 
namespace Alcyon\CoreBundle\Component\ListHelper;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

interface FilterInterface
{    
    /**
     * Returns options
     *
     * @return array
     */
    public function getOptions();      
    
    /**
     * Set options
     *
     * @return ElementInterface
     */
    public function setOptions(array $options = array());
    
    /**
     * Configures the options
     *
     * @param OptionsResolver $resolver The resolver for the options
     */
    public function configureOptions(OptionsResolver $resolver);

    /**
     * Get type of this filter
     *
     * @return Form|null
     */
    public function getType();

    /**
     * Add a filter to form
     *
     * @param string            $name the name of the element in the form
     * @param FormInterface     $form the form     
     *
     * @return FilterInterface the filter
     */
    public function addToForm($name, FormInterface $form);  
    
    /**
     * Return a array of DataFilterInterface  
     *
     * @return DataFilterInterface[] Get DataFilter generated by this filter
     */  
    public function getDataFilters();  
}
