<?php

namespace Alcyon\CoreBundle\Repository;

/**
 * CatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogueRepository extends Repository
{
}
