<?php

namespace Alcyon\CoreBundle\Repository;

use Alcyon\CoreBundle\Repository\Repository;
use Alcyon\CoreBundle\Entity\Catalogue;
/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends Repository
{
    public function qbFindAll()
    {
        return $this->leftJoinParentsAndChilds();
    }

	public function findAll()
	{
		return $this->qbFindAll()->getQuery()->getResult();
	}

	public function qbFindByCatalogueWithParents(Catalogue $catalogue)
    {
        $qb = $this->leftJoinParents(null, 'c');
        $qb ->join('c.catalogue', 'ca', 'WITH', 'ca.id = :idCatalogue')
            ->orderBy('c.ordre','ASC')
            ->setParameters(array('idCatalogue'  => $catalogue->getId()))
        ;

        return $qb;
    }

	public function findByCatalogueWithParents(Catalogue $catalogue)
	{
        return $this->qbFindByCatalogueWithParents($catalogue)->getQuery()->getResult();
	}
}