<?php

namespace Alcyon\CoreBundle\Repository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends Repository
{
}
