<?php

namespace Alcyon\CoreBundle\Repository;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends Repository
{
}
