<?php

namespace Alcyon\CoreBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends Repository
{
	public function getDefault()
	{
		$theme = $this->findOneByTemplate('default');

		return $theme;
	}
	
}
