<?php

namespace Alcyon\ExempleBundle\Repository;

use Alcyon\CoreBundle\Entity\Categorie;
use Alcyon\CoreBundle\Repository\Repository;
use Doctrine\ORM\QueryBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends Repository
{

	public function queryBuilderFindByCategories(Categorie $categorie) : QueryBuilder
	{
		$qb = $this->createQuerybuilder('p');
        $qb ->join('p.categories', 'c', 'WITH', 'c.id = :idCategorie')
            ->addSelect('c')
            ->setParameters(array('idCategorie'  => $categorie->getId()));
            
				
		$qb->orderBy('p.title','ASC');

		return $qb;
	}
}
