<?php

namespace Alcyon\ExempleBundle\Repository;

use Alcyon\CoreBundle\Repository\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends Repository
{
}
